# Copyright The MF-Plugin Contributors
#
# Licensed under the MIT License.
# For details on the licensing terms, see the LICENSE file.
# SPDX-License-Identifier: MIT

"""Contains integration tests for the ANTLR lexer and parser.

The TestLexerAndParser class contains integration tests which loads the test files
for valid and invalid PFDL programs with MF-Plugin components. It is tested whether 
the parser finds no errors in valid files and vice versa.
"""

# standard libraries
import unittest

# 3rd party libs
from antlr4.InputStream import InputStream
from antlr4.error.ErrorListener import ErrorListener
from antlr4.CommonTokenStream import CommonTokenStream

# local sources
## MF-Plugin sources
from pfdl_scheduler.parser.PFDLLexer import PFDLLexer
from pfdl_scheduler.parser.PFDLParser import PFDLParser

VALID_FOLDER_PATH = "pfdl_scheduler/plugins/mf_plugin/tests/test_files/valid/"
INVALID_FOLDER_PATH = "pfdl_scheduler/plugins/mf_plugin/tests/test_files/invalid/syntax/"


class SyntaxErrorListener(ErrorListener):
    """Overrides Antlr ErrorListener class so errors can be counted
    for the integration tests.

    Attributes:
        token_stream: ANTLR CommonTokenStream representing the Tokens from the generated Lexer.
        error_count: Integer representing the total error count (here: syntax error count).
    """

    def __init__(self, token_stream: CommonTokenStream) -> None:
        super()
        self.token_stream: CommonTokenStream = token_stream
        self.error_count: int = 0

    def syntaxError(self, recognizer, offendingSymbol, line, column, msg, e) -> None:
        self.error_count = self.error_count + 1


class TestLexerAndParser(unittest.TestCase):
    """Testcase containing integration tests for the MF-Plugin lexer and parser.

    This class contains integration tests for the MF-Plugin lexer and parser
    generated by ANTLR. The tests check if all possible syntax errors are
    recognized and valid files are passed through.

    Attributes:
        lexer: The generated ANTLR Lexer for the MF-Plugin which should be tested.
        parser: The generated ANTLR Parser for the MF-Plugin which should be tested.
        error_listener: SyntaxErrorListener object for counting the errors.
    """

    def setUp(self) -> None:
        self.lexer: PFDLLexer = None
        self.parser: PFDLParser = None
        self.error_listener: SyntaxErrorListener = None

    def load_file(self, file_path: str) -> None:
        """Loads a file from the given path and parses it if it is a PFDL program."""

        if file_path.endswith(".pfdl"):
            mf_plugin_string = ""
            with open(file_path, "r", encoding="utf8") as file:
                mf_plugin_string = file.read()

            self.lexer = PFDLLexer(InputStream(mf_plugin_string))
            self.lexer.removeErrorListeners()
            token_stream = CommonTokenStream(self.lexer)
            self.parser = PFDLParser(token_stream)
            self.parser.removeErrorListeners()
            self.error_listener = SyntaxErrorListener(token_stream)
            self.lexer.addErrorListener(self.error_listener)
            self.parser.addErrorListener(self.error_listener)
            self.parser.program()

    ###
    #   Test files that are valid PFDL programs (using the MF-Plugin Scheduler)
    ###
    def test_aos_statements(self):
        """Loads a valid test file which contains all possible statements in an AOS."""
        self.load_file(VALID_FOLDER_PATH + "aos_statements.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_attribute_assignment_json(self):
        """Loads a valid test file which assigns a value to an attribute in a JSON manner."""
        self.load_file(VALID_FOLDER_PATH + "attribute_assignment_json.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_comments(self):
        """Loads a valid test file which contains comments on various places."""
        self.load_file(VALID_FOLDER_PATH + "comments.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_complex_expression(self):
        """Loads a valid test file which contains a complex expression
        consisting of different operators."""
        self.load_file(VALID_FOLDER_PATH + "complex_expression.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_every_component(self):
        """Loads a valid test file which contains every possible MF-Plugin component."""
        self.load_file(VALID_FOLDER_PATH + "every_component.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_identifiers(self):
        """Loads a valid test file where all possible identifier combinations are present."""
        self.load_file(VALID_FOLDER_PATH + "identifiers.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_inheritence(self):
        """Loads a valid test file where a Struct with inheritence is defined."""
        self.load_file(VALID_FOLDER_PATH + "inheritence.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_nested_attribute_assignment(self):
        """Loads a valid test file which contains an attribute assignment in an instance which
        defines the attributes for an inherited Struct."""
        self.load_file(VALID_FOLDER_PATH + "nested_attribute_assignment.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_nested_expression(self):
        """Loads a valid test file which contains a nested expression."""
        self.load_file(VALID_FOLDER_PATH + "nested_expression.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_nested_json(self):
        """Loads a valid test file which contains a nested JSON initialization."""
        self.load_file(VALID_FOLDER_PATH + "nested_json.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_new_lines(self):
        """Loads a valid test file which has new lines after every grammar construct."""
        self.load_file(VALID_FOLDER_PATH + "new_lines.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_parameter_values(self):
        """Loads a valid test file where all possible parameter value combinations are present."""
        self.load_file(VALID_FOLDER_PATH + "parameter_values.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_rule_explicit_and(self):
        """Loads a valid test file with explicit 'And' in the expression."""
        self.load_file(VALID_FOLDER_PATH + "rule_explicit_and.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_rule_implicit_and(self):
        """Loads a valid test file with implicit 'And' in the expression."""
        self.load_file(VALID_FOLDER_PATH + "rule_implicit_and.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_task_statements(self):
        """Loads a valid test file which contains all possible statements in a Task."""
        self.load_file(VALID_FOLDER_PATH + "task_statements.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    def test_tos_statements(self):
        """Loads a valid test file which contains all possible statements in a TOS."""
        self.load_file(VALID_FOLDER_PATH + "tos_statements.pfdl")
        self.assertEqual(self.error_listener.error_count, 0)

    ###
    #   Test files that are invalid PFDL programs (using the MF-Plugin Scheduler)
    ###

    # Imports
    def test_import_double_comma(self):
        """Loads an invalid test file in which the import
        statement contains two commas in a row."""
        self.load_file(INVALID_FOLDER_PATH + "import_double_comma.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_import_misspelled(self):
        """Loads an invalid test file in which the import statement is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "import_misspelled.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    # Structs
    def test_struct_colon_missing(self):
        """Loads an invalid test file in which the attribute
        definition in the struct misses a colon.
        """
        self.load_file(INVALID_FOLDER_PATH + "struct_colon_missing.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_struct_empty(self):
        """Loads an invalid test file in which the Struct definition is empty."""
        self.load_file(INVALID_FOLDER_PATH + "struct_empty.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_struct_invalid_attribute_name(self):
        """Loads an invalid test file in which the Struct definition
        contains an attribute with an invalid identifier."""
        self.load_file(INVALID_FOLDER_PATH + "struct_invalid_attribute_name.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_struct_invalid_struct_name(self):
        """Loads an invalid test file in which the Struct identifier is invalid."""
        self.load_file(INVALID_FOLDER_PATH + "struct_invalid_struct_name.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_struct_invalid_type_name(self):
        """Loads an invalid test file in which the attribute type inside a Struct is invalid."""
        self.load_file(INVALID_FOLDER_PATH + "struct_invalid_type_name.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_missing_attribute_identifier(self):
        """Loads an invalid test file in which the attribute identifier
        inside the Struct is missing."""
        self.load_file(INVALID_FOLDER_PATH + "struct_missing_attribute_identifier.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_struct_missing_end(self):
        """Loads an invalid test file in which the 'End' keyword is missing in the Struct."""
        self.load_file(INVALID_FOLDER_PATH + "struct_missing_end.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_struct_missing_struct_identifier(self):
        """Loads an invalid test file in which the Struct identifier is missing."""
        self.load_file(INVALID_FOLDER_PATH + "struct_missing_struct_identifier.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_struct_missing_type(self):
        """Loads an invalid test file in which an attribute within
        the Struct is missing his type."""
        self.load_file(INVALID_FOLDER_PATH + "struct_missing_type.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_struct_misspelled(self):
        """Loads an invalid test file in which the 'Struct' keyword is misspelled"""
        self.load_file(INVALID_FOLDER_PATH + "struct_misspelled.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_struct_wrong_indentation(self):
        """Loads an invalid test file in which the indentation within the Struct is wrong."""
        self.load_file(INVALID_FOLDER_PATH + "struct_wrong_indentation.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    # Instances
    def test_instance_colon_missing(self):
        """Loads an invalid test file in which a colon is missing within the Instance."""
        self.load_file(INVALID_FOLDER_PATH + "instance_colon_missing.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_instance_empty(self):
        """Loads an invalid test file in which the Instance definition is empty."""
        self.load_file(INVALID_FOLDER_PATH + "instance_empty.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_instance_missing_end(self):
        """Loads an invalid test file in which the 'End' keyword is missing in the Instance."""
        self.load_file(INVALID_FOLDER_PATH + "instance_missing_end.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_instance_wrong_indentation(self):
        """Loads an invalid test file in which the indentation within the Instance is wrong."""
        self.load_file(INVALID_FOLDER_PATH + "instance_wrong_indentation.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_instance_invalid_attribute_access(self):
        """Loads an invalid test file in which the attribute access starts with a '.'."""
        self.load_file(INVALID_FOLDER_PATH + "instance_invalid_attribute_access.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_instance_invalid_attribute_name(self):
        """Loads an invalid test file in which an attribute's name
        within the Instance is not an identifier."""
        self.load_file(INVALID_FOLDER_PATH + "instance_invalid_attribute_name.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_instance_invalid_attribute_value(self):
        """Loads an invalid test file in which an attribute's value
        is invalid (not an identifier, number, ...)."""
        self.load_file(INVALID_FOLDER_PATH + "instance_invalid_attribute_value.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    # Rules
    def test_rule_empty(self):
        """Loads an invalid test file in which the Rule definition is empty."""
        self.load_file(INVALID_FOLDER_PATH + "rule_empty.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_rule_invalid_rule_name(self):
        """Loads an invalid test file in which the Rule identifier is invalid."""
        self.load_file(INVALID_FOLDER_PATH + "rule_invalid_rule_name.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_rule_missing_end(self):
        """Loads an invalid test file in which the 'End' keyword is missing in the Rule."""
        self.load_file(INVALID_FOLDER_PATH + "rule_missing_end.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_rule_misspelled(self):
        """Loads an invalid test file in which the 'Rule' keyword is misspelled"""
        self.load_file(INVALID_FOLDER_PATH + "rule_misspelled.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_rule_parameters_invalid_name(self):
        """Loads an invalid test file in which a Rule parameter (the identifier) is invalid."""
        self.load_file(INVALID_FOLDER_PATH + "rule_parameters_invalid_name.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_rule_parameters_trailing_comma(self):
        """Loads an invalid test file in which the Rule parameter list
        contains a trailing comma."""
        self.load_file(INVALID_FOLDER_PATH + "rule_parameters_trailing_comma.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_rule_wrong_indentation(self):
        """Loads an invalid test file in which the indentation within the Rule is wrong."""
        self.load_file(INVALID_FOLDER_PATH + "rule_wrong_indentation.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    # Tasks
    def test_task_empty(self):
        """Loads an invalid test file in which the Task definition is empty."""
        self.load_file(INVALID_FOLDER_PATH + "task_empty.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_float_at_repeat(self):
        """Loads an invalid test file in which the Repeat statement
        receives a float as input within the Task."""
        self.load_file(INVALID_FOLDER_PATH + "task_float_at_repeat.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_id_at_repeat(self):
        """Loads an invalid test file in which the Repeat statement
        receives an identifier as input within the Task."""
        self.load_file(INVALID_FOLDER_PATH + "task_id_at_repeat.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_missing_end(self):
        """Loads an invalid test file in which the 'End' keyword is missing in the Task."""
        self.load_file(INVALID_FOLDER_PATH + "task_missing_end.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_invalid_task_name(self):
        """Loads an invalid test file in which the Task identifier is invalid."""
        self.load_file(INVALID_FOLDER_PATH + "task_invalid_task_name.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled(self):
        """Loads an invalid test file in which the 'Task' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled_action(self):
        """Loads an invalid test file in which the 'Action' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled_action.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled_constraints(self):
        """Loads an invalid test file in which the 'Constraints' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled_constraints.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled_do(self):
        """Loads an invalid test file in which the 'Do' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled_do.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled_finished_by(self):
        """Loads an invalid test file in which the 'FinishedBy' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled_finished_by.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled_from(self):
        """Loads an invalid test file in which the 'From' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled_from.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled_move(self):
        """Loads an invalid test file in which the 'Move' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled_move.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled_on_done(self):
        """Loads an invalid test file in which the 'OnDone' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled_on_done.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled_repeat(self):
        """Loads an invalid test file in which the 'Repeat' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled_repeat.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled_started_by(self):
        """Loads an invalid test file in which the 'StartedBy' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled_started_by.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled_to(self):
        """Loads an invalid test file in which the 'To' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled_to.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_task_misspelled_transport(self):
        """Loads an invalid test file in which the 'Transport' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "task_misspelled_transport.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    # TransportOrderSteps
    def test_tos_empty(self):
        """Loads an invalid test file in which the TransportOrderStep definition is empty."""
        self.load_file(INVALID_FOLDER_PATH + "tos_empty.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_float_at_location(self):
        """Loads an invalid test file in which the Location statement receives a float as input."""
        self.load_file(INVALID_FOLDER_PATH + "tos_float_at_location.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_float_at_on_done(self):
        """Loads an invalid test file in which the OnDone statement receives a float as input."""
        self.load_file(INVALID_FOLDER_PATH + "tos_float_at_on_done.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_int_at_location(self):
        """Loads an invalid test file in which the Location statement
        receives an Integer as input."""
        self.load_file(INVALID_FOLDER_PATH + "tos_int_at_location.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_int_at_on_done(self):
        """Loads an invalid test file in which the OnDone statement
        receives an Integer as input."""
        self.load_file(INVALID_FOLDER_PATH + "tos_int_at_on_done.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_missing_end(self):
        """Loads an invalid test file in which the 'End' keyword
        is missing in the TransportOrderStep."""
        self.load_file(INVALID_FOLDER_PATH + "tos_missing_end.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_misspelled_finished_by(self):
        """Loads an invalid test file in which the 'FinishedBy' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "tos_misspelled_finished_by.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_misspelled_location(self):
        """Loads an invalid test file in which the 'Location' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "tos_misspelled_location.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_misspelled_on_done(self):
        """Loads an invalid test file in which the 'OnDone' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "tos_misspelled_on_done.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_misspelled_parameters(self):
        """Loads an invalid test file in which the 'Parameters' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "tos_misspelled_parameters.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_misspelled_started_by(self):
        """Loads an invalid test file in which the 'StartedBy' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "tos_misspelled_started_by.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_misspelled(self):
        """ "Loads an invalid test file in which the 'TransportOrderStep' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "tos_misspelled.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_tos_invalid_parameter(self):
        """Loads an invalid test file in which the Parameters statement recevies an
        invalid parameter (a text which is not an identifier)."""
        self.load_file(INVALID_FOLDER_PATH + "tos_invalid_parameter.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    # ActionOrderSteps
    def test_aos_empty(self):
        """Loads an invalid test file in which the ActionOrderStep definition is empty."""
        self.load_file(INVALID_FOLDER_PATH + "aos_empty.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_aos_missing_end(self):
        """Loads an invalid test file in which the 'End' keyword is
        missing in the ActionOrderStep."""
        self.load_file(INVALID_FOLDER_PATH + "aos_missing_end.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_aos_misspelled_finished_by(self):
        """Loads an invalid test file in which the 'FinishedBy' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "aos_misspelled_finished_by.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_aos_misspelled_on_done(self):
        """Loads an invalid test file in which the 'OnDone' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "aos_misspelled_on_done.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_aos_misspelled_parameters(self):
        """Loads an invalid test file in which the 'Parameters' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "aos_misspelled_parameters.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_aos_misspelled_started_by(self):
        """Loads an invalid test file in which the 'StartedBy' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "aos_misspelled_started_by.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_aos_misspelled(self):
        """Loads an invalid test file in which the 'ActionOrderStep' keyword is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "aos_misspelled.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    # JSON
    def test_json_missing_closing_bracket(self):
        """Loads an invalid test file in which the JSON initialization misses a closing bracket."""
        self.load_file(INVALID_FOLDER_PATH + "json_missing_closing_bracket.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_json_missing_colon(self):
        """Loads an invalid test file in which a JSON pair in
        the JSON initialization misses a colon."""
        self.load_file(INVALID_FOLDER_PATH + "json_missing_colon.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_json_missing_comma(self):
        """Loads an invalid test file in which the JSON initialization
        misses a comma between pairs."""
        self.load_file(INVALID_FOLDER_PATH + "json_missing_comma.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_json_opening_bracket_in_new_line(self):
        """Loads an invalid test file in which the JSON initialization starts in a new line."""
        self.load_file(INVALID_FOLDER_PATH + "json_opening_bracket_in_new_line.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_json_trailing_comma(self):
        """Loads an invalid test file in which the JSON initialization
        contains a trailing comma."""
        self.load_file(INVALID_FOLDER_PATH + "json_trailing_comma.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_json_array_trailing_comma(self):
        """Loads an invalid test file in which the JSON initialization
        contains a trailing comma in an array."""
        self.load_file(INVALID_FOLDER_PATH + "json_array_trailing_comma.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_json_invalid_value(self):
        """Loads an invalid test file in which the JSON initialization
        contains a pair with an invalid value (no number, no "", ...)."""
        self.load_file(INVALID_FOLDER_PATH + "json_invalid_value.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_json_array_invalid_value(self):
        """Loads an invalid test file in which the JSON initialization
        contains an array with an invalid value (no number, no "", ...)."""
        self.load_file(INVALID_FOLDER_PATH + "json_array_invalid_value.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_json_missing_quotes(self):
        """Loads an invalid test file in which the JSON initialization
        contains a pair where the id is not enclosed in quotes."""
        self.load_file(INVALID_FOLDER_PATH + "json_missing_quotes.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    # Expressions
    def test_expr_invalid_operator_use(self):
        """Loads an invalid test file in which the expression
        contains an '+' in an unvalid position."""
        self.load_file(INVALID_FOLDER_PATH + "expr_invalid_operator_use.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_expr_invalid_un_op(self):
        """Loads an invalid test file in which the expression
        contains an '!' in an unvalid position."""
        self.load_file(INVALID_FOLDER_PATH + "expr_invalid_un_op.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_expr_misspelled_and(self):
        """Loads an invalid test file in which the 'And' keyword
        in the expression is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "expr_misspelled_and.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_expr_misspelled_or(self):
        """Loads an invalid test file in which the 'Or' keyword in the expression is misspelled."""
        self.load_file(INVALID_FOLDER_PATH + "expr_misspelled_or.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)

    def test_expr_missing_closing_parenthesis(self):
        """Loads an invalid test file in which the expression missing a closing parenthesis."""
        self.load_file(INVALID_FOLDER_PATH + "expr_missing_closing_parenthesis.pfdl")
        self.assertGreaterEqual(self.error_listener.error_count, 1)
