// MF-Plugin
RULE: 'Rule';
TRANSPORT: 'Transport';
MOVE: 'Move';
ACTION: 'Action';
FROM: 'From';
DO: 'Do';
ON_DONE: 'OnDone';
TRANSPORT_ORDER_STEP: 'TransportOrderStep';
MOVE_ORDER_STEP: 'MoveOrderStep';
ACTION_ORDER_STEP: 'ActionOrderStep';
CONSTRAINTS: 'Constraints';
PARAMETERS: 'Parameters';
STARTED_BY: 'StartedBy';
FINISHED_BY: 'FinishedBy';
LOCATION: 'Location';
EVENT: 'Event';
TIME: 'Time'